/**
 * Board UI copy. The views i18n rule requires JSX text to pass through useT(),
 * but the locale bundles (`packages/views/locales/`) sit outside this card's
 * file boundary, so copy lives here as named constants and is rendered through
 * expressions. Follow-up (needs a locale-bundle change, outside this card):
 * move these into a `visualization` namespace registered in
 * `packages/views/i18n/resources-types.ts` with translations for all five
 * locales — en strings here are the source for that migration.
 */
export const BOARD_STRINGS = {
  pageTitle: "Scheduling Board",
  searchPlaceholder: "Search identifier, title, assignee… (⌘K)",
  searchLabel: "Search issues",
  filterStatus: "Status",
  filterAssignee: "Assignee",
  filterStatusAll: "All statuses",
  filterAssigneeAll: "All assignees",
  layoutStandard: "Standard layout",
  fitView: "Fit view",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  legend: "Legend",
  legendEdges: "Relations",
  legendParentEdge: "parent hierarchy · solid · parent→child",
  legendAssigneeEdge: "assignee dispatch · dashed · card→assignee",
  legendSquadEdge: "squad membership · dotted · squad→leader→member",
  legendStatuses: "Status (7 built-in + custom)",
  legendLanes: "Lanes",
  legendStageLane: "STAGE n (top-down ascending)",
  legendUnassignedLane: "Ungrouped (stage=null, top)",
  legendFooter:
    "Collapse: only issues with children and squads fold; +n counts hidden descendants. Below 40% zoom nodes degrade to status blocks, below 20% to status dots.",
  legendCollapse: "Collapse legend",
  legendExpand: "Expand legend",
  live: "Live",
  reconnecting: "Reconnecting",
  lastSynced: "Last synced",
  demoData: "Demo data",
  close: "Close",
  openInBoard: "Open in board",
  creator: "Creator",
  stage: "Stage",
  assignee: "Assignee",
  realtime: "Realtime",
  realtimeHint: "Refreshed by issue / agent / task events",
  childProgress: "Subtasks",
  ungroupedLane: "Ungrouped · STAGE=NULL",
  stageLane: "STAGE",
  memberNoName: "Member",
  noAssignee: "Unassigned",
  squadBadge: "SQUAD",
  agentBadge: "AGENT",
  memberBadge: "MEMBER",
  leaderBadge: "LEADER",
  squadMembers: "Members",
  squadLeader: "Leader",
  model: "Model",
  activeWork: "Active",
  actorRuntimeHint: "Runtime status and active-issue counts refresh from agent events once the data layer is connected.",
  expandNode: "Expand",
  collapseNode: "Collapse",
  openDetails: "Open details",
  emptyGraph: "No issues to show",
  narrowViewport: "Please open in a wider window",
  unknownStatus: "Unknown",
  runtimeStatusFallback: "idle",
} as const;
